### ISSUE TITLE
Get sphinx up and running

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#126]
sphinx Git repo here: https://github.com/convexopt/sphinx_gpkit

OUTLINE:
gpkit Documentation
   What is gpkit? ==> README
   Installing Instructions @bqpd 
   Quick Reference Grid 
      ->Includes first example with best practices, matches Examples
   Examples (in order of complexity) @cjk12
      ->Cite Boyd Tutorial
      ->Includes first example with best practices, matches QRG
      ->Best practices box @bqpd 
   Why GP's? (including benefits and convexity) @whoburg @pgkirsch 
   GP Playbook
   Introduction to how to read and understand code @bqpd 
      ->Includes Docstrings
   Sphinx @bqpd

**Comment by whoburg** [comment]
*Priority*

**Comment by pgkirsch** [comment]
Here is a proposed structure (slightly modified from above) for the the documentation. It is ordered as if it were a document rather than a website but I think it captures the necessary hierarchy of information. 

- What is a GP
-----> Concise description
-----> concise summary of benefits
-----> Citation of Hoburg 2012, Boyd tutorial

- What is GPkit?
-----> Like in the README
-----> I think this section could benefit from a really simple flowchart:  User <---> GPkit <---> Solver
- Installation Instructions
-----> As in the README but with distinct installation instructions for each platform

- Getting Started
-----> I believe this should purely be a guide to using gpkit (no command-specific info yet)
-----> I also believe it should be as slap-in-the-face-obvious as stating that you need to cd into a certain directory or add it to your path or whatever (possibly with links to a friendly command line reference). No one ever said "wow this documentation is too obvious, I feel insulted", that person just skipped on to more interesting material. In my mind this section is targeted at someone with no/very little command line experience.

      - Basic Commands
      -----> A list of the most basic commands needed to solve a simple example, like the box example
      -----> This section should be subdivided, if possible, into the commands for "declaring variables", "constructing constraints", "solving" etc...

- Simple Example 1
-----> The box example using the basic commands listed above. No fewer, no more.
----> Well documented at each step

- GPkit Glossary
    - Commands
    - Classes
  
    -----> Sorted alphabetically (and/or if possible for commands, by type as in the basic commands section)
    -----> Full listing of inputs, outputs, optional args, description etc.

- Examples
-----> As many examples as we feel are useful to demonstrate the different capabilities of gpkit
-----> This could include ipython notebooks
-----> Make sure to cite Boyd tutorial

**Comment by bqpd** [comment]
Download https://github.com/convexopt/sphinx_gpkit to get a basic install of sphinx. You may need to install the sphinx python package (`pip install sphinx` should do it)

**Comment by whoburg** [comment]
Close? I think the intent of this ticket has been achieved; any missing items? They should be turned into new tickets with smaller scope.

**Comment by bqpd** [comment]
I'm ready to close this. :)
